spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fitlytic
    username: postgres
    password: Password01
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: my-super-secret-key-for-fitlytic
